### ISSUE TITLE
Removing the sub-modules looks like it broke the Docker build for fatACPC.

### ISSUE THREAD

**Issue by curtcorum** [brainimaccs/brainstem#2]
Removing the sub-modules looks like it broke the Docker build for fatACPC.

BrainSTEM Commit: https://github.com/BrainImAccs/BrainSTEM/commit/f8e93b70e3987c572b45bd7aedd2af8b49b5424c

fatACPC Issue: https://github.com/BrainImAccs/fatbACPC/issues/4

**Comment by crubb** [comment]
Thank you - Will be taken care of in https://github.com/BrainImAccs/fatbACPC/issues/4!
